# Generated by Django 2.1.1 on 2018-09-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='warden',
        ),
        migrations.AddField(
            model_name='warden',
            name='hostel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.Hostel'),
        ),
    ]
