# Generated by Django 2.0.1 on 2018-05-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('S', 'Single Occupancy'), ('D', 'Double Occupancy'), ('B', 'Both Single and Double Occupancy')], default=None, max_length=1),
        ),
    ]
