# Generated by Django 2.0.5 on 2018-05-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_auto_20180522_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='gender',
        ),
    ]
