# Generated by Django 2.1.1 on 2018-09-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_auto_20180922_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='no_dues',
            field=models.BooleanField(default=True),
        ),
    ]
