# Generated by Django 2.0.5 on 2018-05-24 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selection', '0004_auto_20180522_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='caretaker',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='warden',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
