# Generated by Django 2.0.1 on 2018-05-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_auto_20180527_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='room_alloted',
            new_name='room_allotted',
        ),
    ]
