# Generated by Django 2.0.5 on 2018-05-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_auto_20180524_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.Room'),
        ),
    ]
