# Generated by Django 2.0.5 on 2018-05-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0006_auto_20180527_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
