# Generated by Django 2.0.5 on 2018-05-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0007_auto_20180527_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='room_alloted',
            new_name='room_allotted',
        ),
    ]
