# Generated by Django 2.0.5 on 2018-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0012_auto_20180528_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_sem',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
