# Generated by Django 2.0.5 on 2018-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0013_auto_20180528_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='course',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('ECE', 'Electronics and Communication')], default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='current_sem',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('ECE', 'Electronics and Communication')], default=None, max_length=5, null=True),
        ),
    ]
