# Generated by Django 2.0.5 on 2018-05-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0014_auto_20180531_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='current_sem',
            new_name='current_year',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='current_sem',
            new_name='current_year',
        ),
    ]
