# Generated by Django 2.0.5 on 2018-05-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0015_auto_20180531_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='current_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
