# Generated by Django 2.0.5 on 2018-05-31 11:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0018_auto_20180531_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('IT', 'Information Technology'), ('ECE', 'Electronics and Communication')], default=None, max_length=10, null=True),
        ),
    ]
