# Generated by Django 2.0.5 on 2018-05-31 11:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0019_auto_20180531_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='current_year',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None, max_length=9, null=True),
        ),
    ]
