# Generated by Django 2.0.5 on 2018-05-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0020_auto_20180531_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IT', 'Information Technology'), ('ECE', 'Electronics and Communication')], default=None, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='course',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='current_year',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, max_length=10, null=True, to='selection.Course'),
        ),
    ]
