# Generated by Django 2.0.5 on 2018-05-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0021_auto_20180531_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, max_length=10, to='selection.Course'),
        ),
    ]
