# Generated by Django 2.0.5 on 2018-05-31 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0023_auto_20180531_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='current_year',
        ),
        migrations.AlterField(
            model_name='student',
            name='current_year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.Year'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='current_year',
            field=models.ManyToManyField(blank=True, default=None, to='selection.Year'),
        ),
    ]
