# Generated by Django 2.0.5 on 2018-05-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_auto_20180522_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='curr_sem',
            new_name='current_sem',
        ),
    ]
